services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant@sha256:ceb1202133a5a036e8b03e20a10eb113186cc2f871968323c6fc6c3fc4205716 #2026.5.4
    ports:
      - "8123:8123"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      TZ: Europe/Berlin
  matterjs-server:
    container_name: matterjs-server
    image: ghcr.io/matter-js/matterjs-server@sha256:1935c641893cf25f0337dd1aa02af9ae0fa22fb50fe7fa274b4519adb2bb028b #0.7.1
    ports:
      - "5580:5580"
    read_only: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - "./matterjs-server:/data"