services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant@sha256:adb3341e31e03e0048e60d8c1cf952e118a381ae258bb921d3da12a3b27bf0c2 #2026.6.4
    ports:
      - "8123:8123"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      TZ: Europe/Berlin
  matterjs-server:
    container_name: matterjs-server
    image: ghcr.io/matter-js/matterjs-server@sha256:de8a19a722325f08bd07744ca4f58a0afc9db42d583f4ff1fd834b5ced202157 #1.1.2
    environment:
      - PRODUCTION_MODE=true
    ports:
      - "5580:5580"
    read_only: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - "./matterjs-server:/data"