volumes:
  nextcloud:
  db:

services:
  redis:
    container_name: nextcloud-redis
    image: redis@sha256:d146f83b1e0f02fc27c26a50cee39338c736674c5959db84363e6ae3cd9e02d2 #8.6.3-alpine3.23
    restart: always
    command: redis-server
    networks:
      ncnet:
        ipv4_address: 172.18.0.5
  db:
    container_name: nextcloud-db
    image: postgres@sha256:54451ecb8ab38c24c3ec123f2fd501303a3a1856a5c66e98cecf2460d5e1e9d7 #18.3-alpine3.23
    restart: always
    volumes:
      - db:/var/lib/postgresql
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    networks:
      ncnet:
        ipv4_address: 172.18.0.2
  app:
    container_name: nextcloud-app
    image: nextcloud@sha256:90a730e9a3dd290d9626ca64740c4d2fa901b4f231fe4ab6eb0dcf300dbc7271 #33.0.3-apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    networks:
      ncnet:
        ipv4_address: 172.18.0.3
    dns:
      - 192.168.178.57
    links:
      - redis
      
  onlyoffice-ds:
    container_name: onlyoffice-ds
    image: onlyoffice/documentserver@sha256:53a06109f1f4029a78f913a061e14f01bff023d109024073a13d4416b54d2195 #9.3.1.2
    restart: always
    environment:
      - JWT_SECRET=s4cretDA34j5fgsfg
      - USE_UNAUTHORIZED_STORAGE=true
    volumes:
      - ./oods_data:/var/www/onlyoffice/Data‚
      - ./oods_log:/var/log/onlyoffice
    networks:
      ncnet:
        ipv4_address: 172.18.0.6
    dns:
      - 192.168.178.57
      
secrets:
  postgres_db:
    file: /data/compose/nextcloud-config/postgres_db.txt # put postgresql db name in this file
  postgres_password:
    file: /data/compose/nextcloud-config/postgres_password.txt # put postgresql password in this file
  postgres_user:
    file: /data/compose/nextcloud-config/postgres_user.txt # put postgresql username in this file

networks:
  ncnet:
    name: ncnet
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.0/24
         gateway: 172.18.0.1
