services:
  web:
    container_name: nginx-web
    image: nginx@sha256:3fe7a344f234ac4b84817896c9294ffae74eae03fc1ad0ff502457fef5cebef8 #1.31.1-alpine-slim
    volumes:
      - ./templates:/etc/nginx/templates
      - ./ssl:/ssl
      - ./house-site:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      pinet:
        ipv4_address: 172.19.0.100
      ncnet:
        ipv4_address: 172.18.0.100
    extra_hosts:
      - "docker.host:172.18.0.1"
    restart: unless-stopped
networks:
  pinet:
    external: true
    name: pinet
  ncnet:
    external: true
    name: ncnet
