services:
  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=pi5.pws9.local
      - NGINX_PORT=80
    networks:
      - pinet
      - ncnet
networks:
  pinet:
    external: true
    name: pinet
  ncnet:
    external: true
    name: ncnet
